require 'cocoapods-catalyst-support'

# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

use_frameworks!

target 'Sample' do
  pod 'AppCenter/Analytics'
  pod 'Firebase/Analytics'
  pod 'Firebase/Messaging'
  pod 'Firebase/InAppMessaging'
end

catalyst_configuration do
  verbose!

  ios 'Firebase/Analytics'
  ios 'Firebase/Messaging'
  ios 'Firebase/InAppMessaging'
  macos 'AppCenter/Analytics'
end

post_install do |installer|
  installer.configure_catalyst
end
