require 'cocoapods-catalyst-support'


# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

use_frameworks!

target 'Sample' do
  pod 'AppCenter/Analytics'
  pod 'Firebase/Analytics'
end

#Add pods to be excluded from macCatalyst 
catalyst_configuration do
  ios 'Firebase/Analytics'
  mac 'AppCenter/Analytics'
end

debug

post_install do |installer|
	installer.configure_support_catalyst
end
