require 'cocoapods-catalyst-support'

# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

use_frameworks!

target 'Sample' do
  pod 'Firebase/Messaging'
  pod 'Firebase/Functions'
  pod 'Firebase/Crashlytics'
  pod 'Firebase/Analytics'
end

#Configure your macCatalyst dependencies
catalyst_configuration do
	# Uncomment the next line for a verbose output
	# verbose!

  ios 'Firebase/Messaging'
  ios 'Firebase/Functions'
  ios 'Firebase/Crashlytics'
  ios 'Firebase/Analytics'
end

#Configure your macCatalyst App
post_install do |installer|
	installer.configure_catalyst
end
